from django.urls import path, re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^login/?$', views.login, name='login'),
    re_path(r'^logout/?$', views.logout, name='logout'),
    re_path(r'^avatars/?$', views.avatars, name='avatars'),
    re_path(r'^avatars/upload/?$', views.avatar_upload, name='avatar-upload'),
    #re_path(r'^avatars/(?P<avatar_id>\d+)/$', views.avatar_details, name='avatar-details'),
    re_path(r'^avatars/(?P<avatar_id>\d+)/image/?$', views.avatar_image, name='avatar-image'),
    re_path(r'^playlists/?$', views.user_playlists, name='user-playlists'),
    re_path(r'^playlists/(?P<playlist_id>\d+)/?$', views.user_playlist_details, name='user-playlist-details'),
    re_path(r'^projects/?$', views.projects, name='projects'),
    # - By ID
    re_path(r'^projects/(?P<project_id>\d+)/?$', views.project_details, name='project-details'),
    re_path(r'^projects/(?P<project_id>\d+)/actions/?$', views.project_actions, name='project-actions'),
    re_path(r'^projects/(?P<project_id>\d+)/avatars/?$', views.project_avatars, name='project-avatars'),
    #re_path(r'^projects/(?P<project_id>\d+)/avatars/(?P<avatar_id>\d+)/?$', views.project_avatar_details, name='project-avatar-details'),
    re_path(r'^projects/(?P<project_id>\d+)/avatars/upload/?$', views.project_avatar_upload, name='project-avatar-upload'),
    re_path(r'^projects/(?P<project_id>\d+)/avatars/(?P<avatar_id>\d+)/image/?$', views.project_avatar_image, name='project-avatar-image'),
    re_path(r'^projects/(?P<project_id>\d+)/audio/upload/?$', views.project_audio_upload, name='project-audio-upload'),
    re_path(r'^projects/(?P<project_id>\d+)/build_background/upload/?$', views.project_build_background_upload, name='project-build-background-upload'),
    re_path(r'^projects/(?P<project_id>\d+)/build_logo/upload/?$', views.project_build_logo_upload, name='project-build-logo-upload'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/?$', views.project_builds, name='project-builds'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/(?P<build_id>\d+)/?$', views.project_details, name='project-build-details'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/(?P<build_id>\d+)/screenshot.jpg$', views.project_build_screenshot, name='project-build-screenshot'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/(?P<build_id>\d+)/thumbnail.jpg$', views.project_build_thumbnail, name='project-build-thumbnail'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/(?P<build_id>\d+)/video.mp4$', views.project_build_video, name='project-build-video'),
    re_path(r'^projects/(?P<project_id>\d+)/builds/(?P<build_id>\d+)/project.log$', views.project_build_gource_log, name='project-build-project-log'),
    re_path(r'^projects/(?P<project_id>\d+)/edit/?$', views.edit_project, name='project-edit'),
    re_path(r'^projects/(?P<project_id>\d+)/project.log$', views.project_build_gource_log, name='project-project-log'),
    re_path(r'^projects/(?P<project_id>\d+)/queue/?$', views.project_queue_build, name='project-queue-build'),
    re_path(r'^projects/(?P<project_id>\d+)/screenshot.jpg$', views.project_build_screenshot, name='project-latest-build-screenshot'),
    re_path(r'^projects/(?P<project_id>\d+)/thumbnail.jpg$', views.project_build_thumbnail, name='project-latest-build-thumbnail'),
    re_path(r'^projects/(?P<project_id>\d+)/video.mp4$', views.project_build_video, name='project-latest-build-video'),
    # - By slug
    re_path(r'^projects/(?P<project_slug>[-\w]+)/?$', views.project_details, name='project-details'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/avatars/?$', views.project_avatars, name='project-avatars'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/?$', views.project_builds, name='project-builds'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/(?P<build_id>\d+)/?$', views.project_details, name='project-build-details'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/(?P<build_id>\d+)/screenshot.jpg$', views.project_build_screenshot, name='project-build-screenshot'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/(?P<build_id>\d+)/thumbnail.jpg$', views.project_build_thumbnail, name='project-build-thumbnail'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/(?P<build_id>\d+)/video.mp4$', views.project_build_video, name='project-build-video'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/builds/(?P<build_id>\d+)/project.log$', views.project_build_gource_log, name='project-build-project-log'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/edit/?$', views.edit_project, name='project-edit'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/project.log$', views.project_build_gource_log, name='project-project-log'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/queue/?$', views.project_queue_build, name='project-queue-build'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/screenshot.jpg$', views.project_build_screenshot, name='project-latest-build-screenshot'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/thumbnail.jpg$', views.project_build_thumbnail, name='project-latest-build-thumbnail'),
    re_path(r'^projects/(?P<project_slug>[-\w]+)/video.mp4$', views.project_build_video, name='project-latest-build-video'),
    re_path(r'^new/?$', views.new_project, name='new-project'),
    re_path(r'^queue/?$', views.build_queue, name='build-queue'),
    re_path(r'^about/?$', views.about, name='about'),
    # Test views
    re_path(r'^test/log/?', views.fetch_log, name='test-fetch-log'),
    re_path(r'^test/tags/?', views.fetch_tags, name='test-fetch-tags'),
    re_path(r'^test/queue/?', views.test_queue_video, name='test-queue-video'),
    re_path(r'^test/video/?', views.make_video, name='test-make-video'),
    re_path(r'^test/(?P<project_id>\d+)/duration.html?$', views.estimate_video_duration, name='test-video-duration'),
    re_path(r'^test/(?P<project_id>\d+)/duration/?$', views.estimate_project_duration, name='test-project-duration'),
    re_path(r'^test/?', views.index, name='test-home'),
]
