version: "3.7"

services:
    gource_studio:
        image: gource_studio
        container_name: gource_web
        entrypoint: ./wait-for-postgres.sh pgdb ./django-entrypoint.sh
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - appconfig:/etc/gource_studio:ro
            - appdata:/var/run/gource_studio
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - POSTGRES_USER=gource_studio_user
            - POSTGRES_PASSWORD=password
        depends_on:
            - pgdb
            - redis
    celery:
        image: gource_studio
        container_name: gource_celery
        entrypoint: ./wait-for-postgres.sh pgdb ./celery-entrypoint.sh
        volumes:
            - appconfig:/etc/gource_studio:ro
            - appdata:/var/run/gource_studio
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - POSTGRES_USER=gource_studio_user
            - POSTGRES_PASSWORD=password
        depends_on:
            - gource_studio
            - pgdb
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=gource_studio
            - POSTGRES_USER=gource_studio_user
            - POSTGRES_PASSWORD=password
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        container_name: redis

volumes:
    appconfig:
    appdata:
    pgdata:
