# Generated by Django 4.2.9 on 2024-09-18 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gource_studio.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('project_url', models.TextField(blank=True, default='')),
                ('project_url_active', models.BooleanField(default=False)),
                ('project_branch', models.CharField(default='master', max_length=256)),
                ('project_vcs', models.CharField(choices=[('git', 'Git'), ('hg', 'Mercurial')], default='git', max_length=16)),
                ('project_slug', models.SlugField(blank=True, error_messages={'unique': 'Project with this slug already exists.'}, max_length=256, null=True, unique=True)),
                ('project_log', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_project_project_log_path)),
                ('project_log_updated_at', models.DateTimeField(blank=True, null=True)),
                ('project_log_commit_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('project_log_commit_time', models.DateTimeField(blank=True, null=True)),
                ('project_log_commit_preview', models.CharField(blank=True, max_length=128, null=True)),
                ('video_size', models.CharField(choices=[('1024x576', '1024 x 576'), ('1280x720', '1280 x 720'), ('1600x900', '1600 x 900'), ('1920x1080', '1920 x 1080'), ('2560x1440', '2560 x 1440'), ('3840x2160', '3840 x 2160')], default='1280x720', max_length=16)),
                ('build_title', models.CharField(blank=True, default='', max_length=256)),
                ('build_logo', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_project_build_logo_path)),
                ('build_logo_resize', models.BooleanField(default=True)),
                ('build_background', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_project_build_background_path)),
                ('build_background_resize', models.BooleanField(default=True)),
                ('build_audio', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_project_build_audio_path)),
                ('build_audio_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_project_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(gource_studio.core.models.BaseProjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('canceled', 'Canceled'), ('running', 'Running'), ('aborted', 'Aborted'), ('completed', 'Completed'), ('errored', 'Errored')], default='pending', max_length=16)),
                ('project_branch', models.CharField(default='master', max_length=256)),
                ('project_log', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_project_log_path)),
                ('project_log_commit_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('project_log_commit_time', models.DateTimeField(blank=True, null=True)),
                ('project_log_commit_preview', models.CharField(blank=True, max_length=128, null=True)),
                ('project_captions', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_project_captions_path)),
                ('build_logo', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_logo_path)),
                ('build_background', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_background_path)),
                ('build_audio', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_audio_path)),
                ('build_audio_name', models.CharField(blank=True, max_length=256, null=True)),
                ('video_size', models.CharField(choices=[('1024x576', '1024 x 576'), ('1280x720', '1280 x 720'), ('1600x900', '1600 x 900'), ('1920x1080', '1920 x 1080'), ('2560x1440', '2560 x 1440'), ('3840x2160', '3840 x 2160')], default='1280x720', max_length=16)),
                ('content', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_video_build_path)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_video_screenshot_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_video_thumbnail_path)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('queued_at', models.DateTimeField(null=True)),
                ('running_at', models.DateTimeField(null=True)),
                ('aborted_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('errored_at', models.DateTimeField(null=True)),
                ('is_full_build', models.BooleanField(default=True)),
                ('current_build_stage', models.CharField(blank=True, max_length=64, null=True)),
                ('current_build_message', models.CharField(blank=True, max_length=512, null=True)),
                ('stdout', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_stdout_path)),
                ('stderr', models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_stderr_path)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='core.project')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(gource_studio.core.models.BaseProjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectUserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_project_avatar_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_project_avatars', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='core.project')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_global_avatar_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.userplaylist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='UserAvatarAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.useravatar')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='core.project')),
            ],
            options={
                'ordering': ('timestamp',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBuildOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('value_type', models.CharField(max_length=32)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.projectbuild')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectBuildCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.CharField(max_length=256)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='core.projectbuild')),
            ],
            options={
                'ordering': ('timestamp',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserAvatarAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.projectuseravatar')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('avatar', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('value_type', models.CharField(max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.project')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('maintainer', 'Maintainer')], default='viewer', max_length=32)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_groups', to='core.project')),
            ],
            options={
                'ordering': ('-date_added',),
                'unique_together': {('project', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('maintainer', 'Maintainer')], default='viewer', max_length=32)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='projectcaption',
            constraint=models.UniqueConstraint(fields=('project', 'timestamp', 'text'), name='unique_project_caption'),
        ),
        migrations.AlterUniqueTogether(
            name='projectbuildoption',
            unique_together={('build', 'name')},
        ),
        migrations.AddConstraint(
            model_name='projectbuildcaption',
            constraint=models.UniqueConstraint(fields=('build', 'timestamp', 'text'), name='unique_build_caption'),
        ),
    ]
