# Generated by Django 3.1.4 on 2021-03-04 04:21

from django.db import migrations, models
import gource_studio.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_project_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuild',
            name='project_captions',
            field=models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_project_captions_path),
        ),
        migrations.AlterField(
            model_name='projectcaption',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
