# Generated by Django 3.1.4 on 2021-11-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_project_public_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuild',
            name='aborted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projectbuild',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('aborted', 'Aborted'), ('completed', 'Completed'), ('errored', 'Errored')], default='pending', max_length=16),
        ),
    ]
