# Generated by Django 3.1.4 on 2022-03-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_video_size_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_project_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_size',
            field=models.CharField(choices=[('1024x576', '1024 x 576'), ('1280x720', '1280 x 720'), ('1600x900', '1600 x 900'), ('1920x1080', '1920 x 1080'), ('2560x1440', '2560 x 1440'), ('3840x2160', '3840 x 2160')], default='1280x720', max_length=16),
        ),
        migrations.AlterField(
            model_name='projectbuild',
            name='video_size',
            field=models.CharField(choices=[('1024x576', '1024 x 576'), ('1280x720', '1280 x 720'), ('1600x900', '1600 x 900'), ('1920x1080', '1920 x 1080'), ('2560x1440', '2560 x 1440'), ('3840x2160', '3840 x 2160')], default='1280x720', max_length=16),
        ),
    ]
