# Generated by Django 3.2 on 2022-06-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_build_commit_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuild',
            name='build_audio_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_audio_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_branch',
            field=models.CharField(default='master', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectbuild',
            name='project_branch',
            field=models.CharField(default='master', max_length=256),
        ),
        migrations.AlterField(
            model_name='projectcaption',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='projectuseravatar',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='projectuseravataralias',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='useravataralias',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
