# Generated by Django 3.2 on 2022-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_build_audio_cache_and_extend_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
