# Generated by Django 3.2.15 on 2022-08-31 04:52

from django.db import migrations, models
import gource_studio.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_change_bigautofield_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_background',
            field=models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_background_path),
        ),
        migrations.AddField(
            model_name='projectbuild',
            name='build_background',
            field=models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_project_background_path),
        ),
        migrations.AddField(
            model_name='projectbuild',
            name='build_logo',
            field=models.ImageField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_project_logo_path),
        ),
    ]
