# Generated by Django 3.2.15 on 2023-09-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_playlists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='projectbuild',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='projectbuildoption',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='projectoption',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='projectbuild',
            name='current_build_message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='projectbuild',
            name='current_build_stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'Project with this slug already exists.'}, max_length=256, null=True, unique=True),
        ),
    ]
