# Generated by Django 3.2.15 on 2023-09-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_project_build_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBuildCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.CharField(max_length=256)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='core.projectbuild')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
