# Generated by Django 3.2.15 on 2023-09-17 21:48

from django.db import migrations, models
import gource_studio.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_projectbuild_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuild',
            name='build_audio',
            field=models.FileField(blank=True, null=True, upload_to=gource_studio.core.models.get_build_audio_path),
        ),
    ]
