# Generated by Django 3.2.15 on 2023-11-26 03:12

from django.db import migrations

# List of common video defaults to apply to any
# existing projects (as they can now be edited)
LEGACY_DEFAULTS = [
    ('key', 'true', 'bool'),
    ('hide', 'filenames,progress', 'str'),
    ('highlight-users', 'true', 'bool'),
    ('user-scale', '2.0', 'float'),
    ('dir-name-depth', '4', 'int'),
    ('bloom-multiplier', '0.5', 'float'),
]

def populate_default_project_options(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    ProjectOption = apps.get_model("core", "ProjectOption")
    for project in Project.objects.all():
        project_options = list(ProjectOption.objects.filter(project=project).values_list('name', flat=True))
        for option in LEGACY_DEFAULTS:
            # Only add option if the project doesn't already have it
            if option[0] not in project_options:
                ProjectOption.objects.create(
                    project=project,
                    name=option[0],
                    value=option[1],
                    value_type=option[2]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_projectmembergroup_relation'),
    ]

    operations = [
        migrations.RunPython(populate_default_project_options, migrations.RunPython.noop),
    ]
