# Generated by Django 3.2.15 on 2023-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_migrate_default_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_background_resize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='build_logo_resize',
            field=models.BooleanField(default=True),
        ),
    ]
