# Generated by Django 4.2.8 on 2023-12-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_image_resize_flags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectbuildcaption',
            constraint=models.UniqueConstraint(fields=('build', 'timestamp', 'text'), name='unique_build_caption'),
        ),
        migrations.AddConstraint(
            model_name='projectcaption',
            constraint=models.UniqueConstraint(fields=('project', 'timestamp', 'text'), name='unique_project_caption'),
        ),
    ]
