# Generated by Django 4.2.8 on 2024-01-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_caption_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectbuildoption',
            unique_together={('build', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectoption',
            unique_together={('project', 'name')},
        ),
    ]
