# Generated by Django 4.2.8 on 2024-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_projectoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuild',
            name='is_full_build',
            field=models.BooleanField(default=True),
        ),
    ]
